version: "3.7"
services:
  redis:
    hostname: redis
    container_name: "crazy_rocket_redis"
    image: redis:5.0.7-alpine
    ports:
      - "$REDIS_PORT:6379"
    command: ["redis-server", "--appendonly", "yes"]
  postgres:
    hostname: "postgres"
    container_name: "crazy_rocket_postgres"
    image: postgres:11.7-alpine
    ports:
        - "$POSTGRES_PORT:5432"
    environment:
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
  nats:
    build: 
      context: ./docker/nats
    image: nats:latest
    container_name: "crazy_rocket_nats"
    hostname: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "crazy_rocket_zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: "crazy_rocket_kafka"
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock